project:
  type: website
  output-dir: docs

website:
  title: "hyeonjung's blog"
  navbar:
    left:
      - numpy.ipynb
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmos
    css: styles.css



